USE UNIVER;
SELECT GROUPS.FACULTY, STUDENT.NAME, PROGRESS.NOTE 
	FROM STUDENT 
	Inner Join GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	WHERE PROGRESS.NOTE < 4

DECLARE @fuc nvarchar(4), @name nvarchar(30), @mark int
DECLARE Badmark CURSOR LOCAL DYNAMIC
	for SELECT GROUPS.FACULTY, STUDENT.NAME, PROGRESS.NOTE 
		FROM STUDENT 
		Inner Join GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
		Inner Join PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE PROGRESS.NOTE < 4

OPEN Badmark
FETCH Badmark into @fuc, @name, @mark
PRINT cast(@fuc as nvarchar(10)) + ' ' + @name + ' ' + cast(@mark as nvarchar(2))
DELETE PROGRESS WHERE CURRENT OF Badmark
CLOSE Badmark

SELECT GROUPS.FACULTY, STUDENT.NAME, PROGRESS.NOTE 
	FROM STUDENT 
	Inner Join GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	WHERE PROGRESS.NOTE < 4