use UNIVER;
go 

--- соединение таблиц с помощью Inner Join ---
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM Inner Join AUDITORIUM_TYPE
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

----- выборка полей со словом 'компьютер' с помощью предиката like
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM Inner Join AUDITORIUM_TYPE
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE And AUDITORIUM_TYPE.AUDITORIUM_TYPENAME Like '%компьютер%'

----- соединение таблиц без Inner Join ---
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM, AUDITORIUM_TYPE
	where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

----- работа с псевдонимами as ---
SELECT A1.AUDITORIUM, A2.AUDITORIUM_TYPENAME
	From AUDITORIUM_TYPE as A2, AUDITORIUM as A1
		Where A2.AUDITORIUM_TYPE = A1.AUDITORIUM_TYPE

